In [1]:
from __future__ import print_function
import tensorflow as tf

# Print Hello World

In [2]:
hello = tf.constant('Hello, Tensowflow!')

In [3]:
sess = tf.Session()

In [4]:
print(sess.run(hello))

b'Hello, Tensowflow!'


# Basic_operation

In [5]:
a = tf.constant(2)
b = tf.constant(3)

In [6]:
with tf.Session() as sess:
    print('a=2, b=3')
    print("Addition of constant: %i" % sess.run(a+b))
    print("Multiplication of constant: %i" %sess.run(a*b))

a=2, b=3
Addition of constant: 5
Multiplication of constant: 6


In [7]:
c = tf.placeholder(tf.int16)
d = tf.placeholder(tf.int16)

In [8]:
add = tf.add(c,d)
mul = tf.multiply(c,d)

In [9]:
with tf.Session() as sess:
    print("addition of variables: %i" % sess.run(add, feed_dict= {c:2, d:3}))
    print("multiplication of variables: %i" % sess.run(mul,feed_dict= {c:2, d:3}))

addition of variables: 5
multiplication of variables: 6


# Matrix Multiplication

In [10]:
matrix1 = tf.constant([[3.,3.]])

In [11]:
matrix2 = tf.constant([[2.],[2.]])  #produces a 2x1 matrix

In [12]:
product = tf.matmul(matrix1, matrix2)   #multiply both matrix, the position will vary the result

In [13]:
with tf.Session() as sess:
    result = sess.run(product)
    print(result)

[[12.]]


# Eager API

In [3]:
from __future__ import absolute_import, division, print_function
import numpy as np
import tensorflow as tf
import tensorflow.contrib.eager as tfe

In [4]:
print("Setting Eager mode...")
tfe.enable_eager_execution()       #need to restart the kernel

print("Define constant tensors")
a = tf.constant(2)
print("a = %i" % a)
b = tf.constant(3)
print("b = %i" % b)

Setting Eager mode...
Define constant tensors
a = 2
b = 3


In [5]:
print('Running operations, without tf.Session')
c = a+b
print('a+b = %i' % c)

d = a*b
print('a*b = %i' % d)

Running operations, without tf.Session
a+b = 5
a*b = 6


In [7]:
print("Mix operations with Tensors and Numpy Arrays")

a = tf.constant([[2.,1.],[1.,0.]],dtype = tf.float32)
print('Tensor:\n a = %s' % a)

Mix operations with Tensors and Numpy Arrays
Tensor:
 a = tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)


In [8]:
b = np.array([[3.,0.],[5.,1.]],dtype = np.float32)
print('NumpyArray:\n b = %s' %b)

NumpyArray:
 b = [[3. 0.]
 [5. 1.]]


In [9]:
print("Running operations, without tf.Session")

Running operations, without tf.Session


In [10]:
c = a + b
print("a + b = %s" % c)

d = tf.matmul(a, b)
print("a * b = %s" % d)

a + b = tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)
a * b = tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [11]:
print("Iterate through Tensor 'a':")

Iterate through Tensor 'a':


In [12]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
